import { ECC_LEVEL_CODES, QRELEMENTSHAPES } from "./enums";
import { QRSpecs } from "./types";
import { ImageSpecs } from "./types";

// Used for default QR Specs
export const QR_DEFAULTS = {
    ECC_LEVEL: ECC_LEVEL_CODES.M,
    MIN_PREFERRED_VERSION: null,
    FORCE_BYTE_ENCODING: false as const,
    MASK_PATTERN: null,
    USE_MODE_SWITCHING: "auto" as const,
    USE_ECI_SWITCHING: "auto" as const,
    PREFER_ECI: false as const,
    PREFER_BOM: false as const
} as const;

export type QRDefault = typeof QR_DEFAULTS[keyof typeof QR_DEFAULTS];

// A Preconfigured default QR Spec if the developer doesn't provide one
export const DEFAULT_QR_SPECS: QRSpecs = {
    eccLevel: QR_DEFAULTS.ECC_LEVEL,
    minPreferredVersion: QR_DEFAULTS.MIN_PREFERRED_VERSION,
    forceByteEncoding: QR_DEFAULTS.FORCE_BYTE_ENCODING,
    maskPattern: QR_DEFAULTS.MASK_PATTERN,
    useModeSwitching: QR_DEFAULTS.USE_MODE_SWITCHING,
    useECISwitching: QR_DEFAULTS.USE_ECI_SWITCHING,
    preferECI: QR_DEFAULTS.PREFER_ECI,
    preferBOM: QR_DEFAULTS.PREFER_BOM
};

// Used for default Image Specs
export const IMAGE_DEFAULTS = {
    BACKGROUND_COLOR: "#FFFFFF",
    MODULE_COLOR: "#000000",
    FINDER_PATTERN_OUTLINE_COLOR: ["#000000", "#000000", "#000000"],
    FINDER_PATTERN_INNER_BACKGROUND_COLOR: ["#FFFFFF", "#FFFFFF", "#FFFFFF"],
    FINDER_PATTERN_INNER_COLOR: ["#000000", "#000000", "#000000"],
    ALIGNMENT_PATTERN_OUTLINE_COLOR: "#000000",
    ALIGNMENT_PATTERN_INNER_BACKGROUND_COLOR: "#FFFFFF",
    ALIGNMENT_PATTERN_INNER_COLOR: "#000000",
    GRID_STROKE_COLOR: "#000000",

    MODULE_SHAPE: QRELEMENTSHAPES.SQUARE,
    FINDER_PATTERN_OUTLINE_SHAPES: [QRELEMENTSHAPES.SQUARE, QRELEMENTSHAPES.SQUARE, QRELEMENTSHAPES.SQUARE],
    FINDER_PATTERN_INNER_BACKGROUND_SHAPES: [QRELEMENTSHAPES.SQUARE, QRELEMENTSHAPES.SQUARE, QRELEMENTSHAPES.SQUARE],
    FINDER_PATTERN_INNER_SHAPES: [QRELEMENTSHAPES.SQUARE, QRELEMENTSHAPES.SQUARE, QRELEMENTSHAPES.SQUARE],
    ALIGNMENT_PATTERN_OUTLINE_SHAPES: QRELEMENTSHAPES.SQUARE,
    ALIGNMENT_PATTERN_INNER_BACKGROUND_SHAPES: QRELEMENTSHAPES.SQUARE,
    ALIGNMENT_PATTERN_INNER_SHAPES: QRELEMENTSHAPES.SQUARE,

    ROUNDNESS: 0.7, // 0-1 for rounded shapes
    GRID_STROKE_WIDTH: 0 // 0-1 for percent
} as const;

export type ImageDefault = typeof IMAGE_DEFAULTS[keyof typeof IMAGE_DEFAULTS];

// A Preconfigured default Image Spec if the developer doesn't provide one
export const DEFAULT_IMAGE_SPECS: ImageSpecs = {
    backgroundColor: IMAGE_DEFAULTS.BACKGROUND_COLOR,
    moduleColor: IMAGE_DEFAULTS.MODULE_COLOR,
    finderPatternOutlineColor: [...IMAGE_DEFAULTS.FINDER_PATTERN_OUTLINE_COLOR],
    finderPatternInnerBackgroundColor: [...IMAGE_DEFAULTS.FINDER_PATTERN_INNER_BACKGROUND_COLOR],
    finderPatternInnerColor: [...IMAGE_DEFAULTS.FINDER_PATTERN_INNER_COLOR],
    alignmentPatternOutlineColor: IMAGE_DEFAULTS.ALIGNMENT_PATTERN_OUTLINE_COLOR,
    alignmentPatternInnerBackgroundColor: IMAGE_DEFAULTS.ALIGNMENT_PATTERN_INNER_BACKGROUND_COLOR,
    alignmentPatternInnerColor: IMAGE_DEFAULTS.ALIGNMENT_PATTERN_INNER_COLOR,
    gridStrokeColor: IMAGE_DEFAULTS.GRID_STROKE_COLOR,

    moduleShape: IMAGE_DEFAULTS.MODULE_SHAPE,
    finderPatternOutlineShapes: [...IMAGE_DEFAULTS.FINDER_PATTERN_OUTLINE_SHAPES],
    finderPatternInnerBackgroundShapes: [...IMAGE_DEFAULTS.FINDER_PATTERN_INNER_BACKGROUND_SHAPES],
    finderPatternInnerShapes: [...IMAGE_DEFAULTS.FINDER_PATTERN_INNER_SHAPES],
    alignmentPatternOutlineShapes: IMAGE_DEFAULTS.ALIGNMENT_PATTERN_OUTLINE_SHAPES,
    alignmentPatternInnerBackgroundShapes: IMAGE_DEFAULTS.ALIGNMENT_PATTERN_INNER_BACKGROUND_SHAPES,
    alignmentPatternInnerShapes: IMAGE_DEFAULTS.ALIGNMENT_PATTERN_INNER_SHAPES,

    roundness: IMAGE_DEFAULTS.ROUNDNESS,
    gridStrokeWidth: IMAGE_DEFAULTS.GRID_STROKE_WIDTH
}